name: Python package

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean & Create cache folders
        run: |
          rm -rf dist/
          rm -rf .cache/
          mkdir -p .cache/reports
          mkdir -p .cache/media
          mkdir -p .cache/docs

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python version
        run: |
          python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade nox build twine pip-tools
          python -m pip install --upgrade virtualenv sphinx
          pip-compile --extra dev pyproject.toml 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Unit tests suite
        run: |
          nox --session tests

# Make fail: nox package install
#      - name: Build package
#        run: |
#          nox --session build
#          ls -lh dist/
#
#      - name: Check package
#        run: |
#          twine check dist/*

      - name: Documentation
        run: |
          nox --session package install
          nox --session notebooks docs

      - name: Collect report artifacts
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: .cache/reports

      - name: Collect package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: |
            dist

      - name: Collect media artifacts
        uses: actions/upload-artifact@v3
        with:
          name: media
          path: .cache/media

      - name: Collect notebooks artifacts
        uses: actions/upload-artifact@v3
        with:
          name: notebooks
          path: docs/source/notebooks

      - name: Collect documentation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: .cache/docs
