name: Python package

on:
  push:
    branches:
      - master
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox build twine pip-tools
          pip-compile pyproject.toml
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Unit Test Suite
        run: |
          nox --session tests

      - name: Documentation
        run: |
          nox --session notebooks docs

      - name: Package
        run: |
          python -m build

      - name: Check package
        run: |
          twine check dist/*
